[package]
name = "popcap_framework-sys"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.59.0"
cc = "1.0.50"
